project_id         = "REPLACE ME"
region             = "asia-south1"
cluster_name       = "gitops-quickstart"
kubernetes_version = "1.23."
release_channel    = "stable"
gitops_repo        = "https://github.com/kameshsampath/gitops-quickstart.git"
gitgitops_repo_revision = "main"