apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-kind
  namespace: harness-delegate-ng
spec:
  template:
    spec:
      volumes:
        - name: harness-tutorial-credentials
          secret:
            secretName: harness-tutorial-credentials
      containers:
        - name: delegate
          env:
            - name: INIT_SCRIPT
              value: |
                microdnf install gzip unzip python3
                curl -sSL "$GCLOUD_CLI_ARTIFACT" | tar zx
                ./google-cloud-sdk/install.sh
                ./google-cloud-sdk/bin/gcloud auth activate-service-account --key-file="$GOOGLE_APPLICATION_CREDENTIALS"
                curl -sSL -o terraform.zip "$TERRAFORM_CLI_ARTIFACT"
                unzip terraform.zip
                mv ./terraform /usr/bin/
                curl -sSL "https://github.com/sigstore/cosign/releases/download/v1.6.0/cosign-linux-amd64" -O /usr/local/bin/cosign
                chmod +x /usr/local/bin/cosign
          volumeMounts:
            - name: harness-tutorial-credentials
              mountPath: /harness-tutorial
              readOnly: true
