destination:
  server: https://kubernetes.default.svc
source:
  # When forked updated to your fork
  repoURL: https://github.com/kameshsampath/go-hello-world-gitops.git
  # the branch to use
  targetRevision: main
argocd:
  imageUpdater:
    version: 0.8.1